# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: typescript-representer / pr

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout PR
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

      - name: Use Node.js LTS (14.x)
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
        with:
          node-version: 14.x

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint code
        run: yarn lint

  ci:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies and run tests
        run: yarn install --frozen-lockfile
